package token

type TokenType uint32

const (
	UNKNOWN_TOKEN_TYPE TokenType = iota
	EOL_TOKEN_TYPE
	WHITESPACE_TOKEN_TYPE
	IDENT_TOKEN_TYPE
	DOT_TOKEN_TYPE
	NUMBER_TOKEN_TYPE
	QUOTE_TOKEN_TYPE
	SLASH_TOKEN_TYPE
	REVERSE_TOKEN_TYPE
	COLON_TOKEN_TYPE
	PLUS_TOKEN_TYPE
	COMPARE_TOKEN_TYPE
	MINUS_TOKEN_TYPE
	FUZZY_TOKEN_TYPE
	BOOST_TOKEN_TYPE
	WILDCARD_TOKEN_TYPE
	LPAREN_TOKEN_TYPE
	RPAREN_TOKEN_TYPE
	LBRACK_TOKEN_TYPE
	RBRACK_TOKEN_TYPE
	LBRACE_TOKEN_TYPE
	RBRACE_TOKEN_TYPE
	AND_TOKEN_TYPE
	SOR_TOKEN_TYPE
	NOT_TOKEN_TYPE
)
